### PR TITLE
Old site

### PR DESCRIPTION
**Pull request by Ansh1693**

### CODE REVIEW

**Comment by MR-DHRUV** [comment]
Bug Fixes

**Comment by Kashishjain04** [comment]
Please replace `<a>` tags with `<Link>` tags to avoid reloading everytime.

**Comment by Kashishjain04** [comment]
Merge conflicts resolved

**Comment by Kashishjain04** [comment]
image
Update this content

**Review by Kashishjain04 — APPROVED** [review]
Looking perfect as of now.
Kudos @Ayush-Baliyan-19 @Ansh1693 @MR-DHRUV @Divyansh3021 @Aeron2 @ShiveshNandan @ola-nishant @kartikkc

**Pull request merged**
